version: '3'
services:
  carml:
    build: .
    ports:
    - 80:80
  zipkin:
    image: openzipkin/zipkin:1.29
    ports:
    - 9411:9411
  consul:
    image: consul
    ports:
    - 8500:8500
  # graylog-mongo:
  #   image: mongo:3
  # graylog-elasticsearch:
  #   image: elasticsearch:2
  #   command: "elasticsearch -Des.cluster.name='graylog'"
  # graylog:
  #   image: graylog/graylog:2.3
  #   environment:
  #     GRAYLOG_PASSWORD_SECRET: somepasswordpepper
  #     GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
  #     GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
  #   links:
  #     - graylog-mongo:mongo
  #     - graylog-elasticsearch:elasticsearch
  #   ports:
  #     - 9000:9000
  caffe2:
    image: carml/caffe-agent:amd64-cpu-latest
